### ISSUE TITLE
Write test for new parameter handling

### ISSUE THREAD

**Issue by JensAc** [IENT/RDPlot#11]
Due to the new implementation of parameter handling the gui tests fail. 
That is actually a problem of the tests and not of the software at the moment.

**Comment by nolyn** [comment]
I believe the test can not be fixed without changing some of the rdplot code too. This is because the pop up is created on the fly, I think it will be very difficult if not impossible to close it in the test function which would allow execution to continue
I see two ways to solve this:
-  Instead of using a pop up, add list of parameters to the GUI. QListView or similar. Either two views, where parameters can be ordered by dragging (as now) or one view using multiple selection.
- Adding a parameter which can be set by the test code and modifies the behaviour such that the pop up is not created

**Comment by nolyn** [comment]
I hacked the second approach as a workaround into the code. the pop up is not created it the environment variable RUNNING_AS_UNITTEST exists.
Not closing this issue, since I think this should be solved in another way

**Comment by JensAc** [comment]
IMHO, @jkuntzer solved the issue. Therefore, I am closing this for now.
