### ISSUE TITLE
Automatic zoom not working when using MS-SSIM

### ISSUE THREAD

**Issue by nolyn** [IENT/RDPlot#41]
MS-SSIM values are often quite close to 1. When using RDPlot, the default plot would look like the example below:

![image](https://user-images.githubusercontent.com/5878536/132866766-6581a200-b7d3-4f56-a0cb-10164905f3b6.png)

The reason are the following lines:
https://github.com/IENT/RDPlot/blob/675f4fe36268f93b84fe22f65d7890fe967d86de/src/rdplot/Widgets/PlotWidget.py#L237-L241

The range of MS-SSIM is 0 to 1, so this creates ticks at 0 and 0.5. Commenting these lines makes the plot appear much nicer. I'm not sure what they are supposed to do, more accuracy of the ticks in some cases I think. If commenting is not acceptable let me know what it should do - I'll see if I can improve it.

**Comment by JensAc** [comment]
I think this was due to a meaningful behavior in case of PSNR values. However, I totally agree that these hardcoded tikz should not be a general limitation. What about checking the axis label, and setting the tikz in dependence of that? For e.g. `dB` these `0.5` most probably makes sense. For SSIM, we could simply do nothing?!

**Comment by nolyn** [comment]
I've create PR #43 to address this

**Comment by JensAc** [comment]
As PR #43 was merged, I close this.
